### ISSUE TITLE
Unhandled Exception: 'entry.route._popCompleter.isCompleted': is not true

### ISSUE THREAD

**Issue by Poweranimal** [lulupointu/vrouter#116]
Hi there,

Using `VNester` with nested routes can break the routing in a specific scenario (which can occur quite often) and cause the following error:

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 5083 pos 14: 'entry.route._popCompleter.isCompleted': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
#2      NavigatorState.pop (package:flutter/src/widgets/navigator.dart:5083:14)
#3      NavigatorState.maybePop (package:flutter/src/widgets/navigator.dart:5034:9)
<asynchronous suspension>
```

The scenario is quite difficult to explain in text, so I added a working example to this issue.
The example is 100% based on [Advanced: Custom VRouteElement And Scaling](https://vrouter.dev/guide/Advanced/Custom%20VRouteElement%20And%20Scaling/Scaling) and only adds one additional nested page (which will cause the error).

In order to reproduce the error, run the app and do the following:
1. On the screen `Shop`, press the button `Show Item (NESTED)`
2. Press the bottom navigation bar item `Profile`
3. Press the bottom navigation bar item `Shop`
4. Press the button `Show Item (NESTED)`
5. Press the pop/back button on the top left to dismiss the page `Item`

Following these steps, will cause the above described error.

<details>
  <summary>Example Code</summary>

```dart
import 'package:flutter/material.dart';
import 'package:vrouter/vrouter.dart';

main() {
  runApp(
    VRouter(
      initialUrl: '/shop',
      routes: [
        ShopRoute(),
        ProfileRoute(),
      ],
    ),
  );
}

class ShopRoute extends VRouteElementBuilder {
  static final String shop = '/shop';
  static final String item = shop + '/item';
  static final String order = shop + '/order';

  @override
  List<VRouteElement> buildRoutes() {
    return [
      ScaffoldRouteElement(
        path: shop,
        nestedRoute: VWidget(
          path: null,
          aliases: [order],
          widget: ContentScreen(
            title: 'Shop',
            actions: [
              ContentScreenAction(
                title: 'Show Order',
                action: (context) => context.vRouter.to(order),
              ),
              ContentScreenAction(
                title: 'Show Item (NESTED)',
                action: (context) => context.vRouter.to(item),
              ),
            ],
          ),
          key: ValueKey('Shop'),
          stackedRoutes: [
            VWidget(
              path: item,
              widget: ContentScreen(title: 'Item'),
            )
          ]
        ),
        stackedRoute: VWidget(
          path: order,
          widget: ContentScreen(title: 'Order'),
        ),
      )
    ];
  }
}

class ProfileRoute extends VRouteElementBuilder {
  static final String profile = '/profile';
  static final String settings = profile + '/settings';

  @override
  List<VRouteElement> buildRoutes() {
    return [
      ScaffoldRouteElement(
        path: profile,
        nestedRoute: VWidget(
          path: null,
          aliases: [settings],
          widget: ContentScreen(
            title: 'Profile',
            actions: [
              ContentScreenAction(
                title: 'Show Settings',
                action: (context) => context.vRouter.to(settings),
              ),
            ],
          ),
          key: ValueKey('Profile'),
        ),
        stackedRoute: VWidget(path: settings, widget: ContentScreen(title: 'Settings')),
      )
    ];
  }
}

class ScaffoldRouteElement extends VRouteElementBuilder {
  static final navigatorKey = GlobalKey<NavigatorState>();

  final String path;
  final VRouteElement nestedRoute;
  final VRouteElement stackedRoute;

  ScaffoldRouteElement({required this.path, required this.nestedRoute, required this.stackedRoute});

  @override
  List<VRouteElement> buildRoutes() {
    return [
      VNester(
        key: ValueKey('MyScaffold'),
        navigatorKey: navigatorKey,
        path: path,
        widgetBuilder: (child) => MyScaffold(body: child),
        nestedRoutes: [nestedRoute],
        stackedRoutes: [stackedRoute],
      )
    ];
  }
}

class MyScaffold extends StatelessWidget {
  const MyScaffold({required this.body});
  final Widget body;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: body,
      bottomNavigationBar: BottomNavigationBar(
        items: [
          BottomNavigationBarItem(
            icon: Icon(Icons.shop),
            label: 'Shop',
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.person),
            label: 'Profile',
          ),
        ],
        currentIndex: context.vRouter.path.startsWith(ProfileRoute.profile) ? 1 : 0,
        onTap: (value) => context.vRouter.to(value == 0 ? ShopRoute.shop : ProfileRoute.profile),
      ),
    );
  }
}

class ContentScreenAction {
  const ContentScreenAction({required this.title, required this.action});
  final String title;
  final Function(BuildContext) action;
}

class ContentScreen extends StatelessWidget {
  const ContentScreen({required this.title, this.actions = const []});
  final String title;
  final List<ContentScreenAction> actions;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text(title)),
      body: Center(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            Text(title),
            if (actions.isNotEmpty)
              ...actions.map((e) => ElevatedButton(
                onPressed: () => e.action(context),
                child: Text(e.title),
              ))
          ],
        ),
      ),
    );
  }
}
```
</details>

**Comment by lulupointu** [comment]
I can reproduce the issue.

I have no idea what is causing this but I will investigate and let you know as soon as as know (and eventually as soon as a fix is out)

Thanks for the well written issue, a delight to work with :wink:

**Comment by lulupointu** [comment]
I have tracked the issue. This is indeed an issue with VRouter.

I'll fix it and let you know

**Comment by Poweranimal** [comment]
Perfect, thank you very much.

**Comment by lulupointu** [comment]
A fix has been found and implemented. 

This needs more testing but hopefully this will be fixed within days.

**Comment by Poweranimal** [comment]
Hi @lulupointu ,
Can you give an approximate time estimation when the next update is available that fixes this bug?
Is there something I can help you with?

**Comment by lulupointu** [comment]
The fix I had found was proving hard to implement. I stopped thinking about it for 2 days I looked again today. The solution appeared to me. This is fixed in `v1.2.0+6` and a test has been added so that this bug will not appear again.

Sorry again for the delay, I'm pretty busy atm.

Feel free to close ones you verified the fix on your side.

**Comment by Poweranimal** [comment]
Thank you very much.
I highly appreciate your effort.

**Comment by Poweranimal** [comment]
Hi @lulupointu ,
Thank you very much for the fix.
I've seen it involved a lot of changes :smile:

For the most parts, it works great and the bug doesn't appear anymore.

However, in some very specific situations it can still occur.
I'm trying to setup up a reproducible environment, but haven't succeeded yet.
I'll let you know, when I managed to set it up.

**Comment by lulupointu** [comment]
Oh I'm very sorry there is still an issue.

I tried producing a bug with complex example but couldn't. I'm very interested in a reproducible issue!

**Comment by Poweranimal** [comment]
Still having big difficulties to reproduce...
Maybe I accidentally built the app with version 1.0.2+5

I'll keep this issue open for a couple of days until I made a new release of my app. Maybe this bug reoccurs during development and testing. 

But I wish it won't 😊

**Comment by lulupointu** [comment]
Perfect, be sure to let me know!

**Comment by Poweranimal** [comment]
Seemed to be a caching issue with flutter pub on my end.

The issue hasn't appeared anymore 🥳

Thanks a lot for the fix!
