### ISSUE TITLE
How does the route stack work?

### ISSUE THREAD

**Issue by felixwortmann** [lulupointu/vrouter#38]
This might well be just me not using the library in the intended way, since I can not figure it out with the docs here is my problem:<br>

This is my VRouter Setup.
```dart
VRouter(
        title: Constants.APP_NAME,
        key: NavigationService.NAVIGATOR_KEY,
        debugShowCheckedModeBanner: false,
        localizationsDelegates: LOCALIZATION_DELEGATES,
        supportedLocales: SUPPORTED_LOCALES,
        localeResolutionCallback: _localeResCallback,
        initialUrl: initialUrl ?? '/',
        routes: [
          VGuard(
            stackedRoutes: [
              VWidget(
                path: '/',
                name: '/',
                widget: HomePage(),
                stackedRoutes: [
                  VWidget(
                    name: '/details',
                    path:
                        '/details/:item',
                    widget: const DetailsPage(),
                  ),
                  VWidget(
                    path: '/add',
                    aliases: const [
                      '/add/:item'
                    ],
                    name: '/add',
                    widget: AddPage(),
                  ),
                ],
              ),
              //...some more routes
        ],
      );
```

I navigate by using:
```dart
  void navigateTo(
    String routeName, {
    Map<String, String> pathParameters = const {},
  }) =>
      NAVIGATOR_KEY.currentState!.pushNamed(
        routeName,
        pathParameters: pathParameters,
      );
```

If I call `navigateTo('/add')` from `HomePage` everything works as expected. If I pop again, I land back on the `HomePage`.<br><br>

If I start at `HomePage`, then `navigateTo('/details',pathParameters:params)` and from `DetailsPage` I call `navigateTo('/add')`, everything looks fine. <br><br>The problem occurs if I pop again after that. My expectation is that the History Stack would be `/home -> /details -> /add`, which would end up in `/details` when popped. It does end up in `/home` though.<br>

I also tried logging the Stack using `historyState` like so:
```dart
  void navigateTo(
    String routeName, {
    Map<String, String> pathParameters = const {},
  }) {
    NAVIGATOR_KEY.currentState!.pushNamed(
      routeName,
      pathParameters: pathParameters,
    );
    print(NAVIGATOR_KEY.currentState!.historyState);
  }
```
That just always prints `{}` after each push.<br>
Did I do something wrong or could this be a problem with the library? I know there is the `VRouterModes.history` Parameter, but it just says that is gets rid of the `/#/`

**Comment by lulupointu** [comment]
A few things first:
1. `historyState` nas nothing to do with the stack, if you want to learn more check https://vrouter.dev/guide/Examples/History%20State
2. You are right, `VRouterModes.history` is not the issue, it really only removes the `/#/`

The issue is that you don't understand how push works (this might be due to poor naming, I am thinking about changing since you are not the first, so sorry about that). 
What I mean by `push` is to push a new path into the web history stack (nothing to do with widgets really, just old browser stuff).

However **the concept of stack does exists**, and is dictated with the way you form you routes. 
For example when your write:
```dart
VWidget(
  path: '/',
  name: '/',
  widget: HomePage(),
  stackedRoutes: [
    VWidget(
      name: '/details',
      path:
          '/details/:item',
      widget: const DetailsPage(),
    ),
    VWidget(
      path: '/add',
      aliases: const [
        '/add/:item'
      ],
      name: '/add',
      widget: AddPage(),
    ),
  ],
),
``` 
You create 3 possible stacks:
* `HomePage`
* `HomePage` -> `DetailsPage`
* `HomePage` -> `AddPage`

So if you are on `/details`, the stack is `HomePage` -> `DetailsPage`, so if you pop you go onto `HomePage`
Similarly if you are on `/add`, the stack is `HomePage` -> `AddPage`, so if you pop you go also onto `HomePage`

If you want that poping from `AddPage` leads you to `DetailsPage`, you have 2 possible way (the best one is the one which is the best for you, there are no preferred way).

**1. Stack `AddPage` on top of `DetailsPage`:
```dart
VWidget(
  path: '/',
  name: '/',
  widget: HomePage(),
  stackedRoutes: [
    VWidget(
      name: '/details',
      path:
      '/details/:item',
      widget: const DetailsPage(),
      stackedRoutes: [
        VWidget(
          path: '/add',
          aliases: const [
            '/add/:item'
          ],
          name: '/add',
          widget: AddPage(),
        ),
      ]
    ),
  ],
)
```

also you should consider using `add` as a relative path instead of `/add/:item`, otherwise pop can't know what are the new pathParameters. Or else note that you can use `pathParameters` if you pop with `vRouter.pop`.

**2. Use a `VPopHandler` to redirect when popping**
```dart
VWidget(
  path: '/',
  name: '/',
  widget: HomePage(),
  stackedRoutes: [
    VWidget(
      name: '/details',
      path: '/details/:item',
      widget: const DetailsPage(),
    ),
    VPopHandler(
      onPop: (vRedirector) async => vRedirector.push('/details/?${vRedirector.previousVRouterData?.pathParameters['item'] ?? '0'}'),
      stackedRoutes: [
        VWidget(
          path: '/add',
          aliases: const ['/add/:item'],
          name: '/add',
          widget: AddPage(),
        ),
      ],
    ),
  ],
)
```

The most important thing really is to understand how path and stack are formed. From there the sky is the limit!

**Comment by felixwortmann** [comment]
Am I understanding this right, so if I would use your first solution and I would pop from `/add`, I would always land on `/details`, even if it was pushed from `/`? Is it possible to go back to the Widget I came from like the "regular" Navigator does?

**Comment by lulupointu** [comment]
> Is it possible to go back to the Widget I came from like the "regular" Navigator does?

No it's not. Because of the way `VRouter` works, privileging `url` over `stack`, you cannot do exactly the same.
To `VRouter`, if a route exist, you have to specify it. 

However this does not mean that what you are trying to do is not possible, just that you need to think differently.
Here is an example to achieve what you ask:

```dart

```

In the example above you have:
* path `/` | stack `HomePage`
* path `/details/:item` | stack `HomePage` -> `DetailsPage`
* path `/details/:item/add/:item` | stack `HomePage` -> `DetailsPage` -> `AddPage` 
* path `/add/:item` | stack `HomePage`-> `AddPage`

Since you can use `push` with a relative path, `push('add/0')` will lead to:
* `/add/:item` if you are in `HomePage`
* `/details/:item/add/:item` if you are in `DetailsPage`

As you see anything is possible, you just really have to think in terms of navigation by path and the fact that 1 path = 1 route stack

**Comment by felixwortmann** [comment]
First of all thanks for your response.
I have implemented it and there is still one thing I can not get working. <br>
If I am on the path `/details/:item/add/:item` and I call `pop()`, the App closes itself, which according to the docs means that no VWidgets were found below this path. Which is not the way it is supposed to be. <br>
This is the basic way and how I call `pop()`
```dart
print('before pop: ${context.vRouter.url}'); //prints the path '/details/a63d84f1-344e-414d-a7ea-06d6f7970770/add/a63d84f1-344e-414d-a7ea-06d6f7970770
context.vRouter.pop();
print('after pop: ${context.vRouter.url}'); //prints the same path '/details/a63d84f1-344e-414d-a7ea-06d6f7970770/add/a63d84f1-344e-414d-a7ea-06d6f7970770
```
I found this as a workaround which achieves what I want. Since I am not using `pop()` here, I assume that this is not the way 
it is supposed to be used. 
```dart
context.vRouter.push(context.vRouter.previousUrl!);
```
Is there a better way to do this? / What could be the problem, why the regular `pop()` is not working how I want it to in the first place?

**Comment by felixwortmann** [comment]
First of all thanks for your response.
I have implemented it and there is still one thing I can not get working. <br>
If I am on the path `/details/:item/add/:item` and I call `pop()`, the App closes itself, which according to the docs means that no VWidgets were found below this path. Which is not the way it is supposed to be. <br>
This is the basic way and how I call `pop()`
```dart
print('before pop: ${context.vRouter.url}'); //prints the path '/details/a63d84f1-344e-414d-a7ea-06d6f7970770/add/a63d84f1-344e-414d-a7ea-06d6f7970770
context.vRouter.pop();
print('after pop: ${context.vRouter.url}'); //prints the same path '/details/a63d84f1-344e-414d-a7ea-06d6f7970770/add/a63d84f1-344e-414d-a7ea-06d6f7970770
```
I found this as a workaround which achieves what I want. Since I am not using `pop()` here, I assume that this is not the way 
it is supposed to be used. 
```dart
context.vRouter.push(context.vRouter.previousUrl!);
```
Is there a better way to do this? / What could be the problem, why the regular `pop()` is not working how I want it to in the first place?

**Comment by lulupointu** [comment]
If you are calling pop without giving `:item` path parameter `vrouter` will think that you don't want to pop to `/detail/:item`. I admit that this is kind of misleading and should instead print an error message.
anyway if you pass the right pass parameter it should work 😊

**Comment by lulupointu** [comment]
Done. It now works as you expect and what you did will work! Be sure to be on  `VRouter >= v1.1.0+20`

**Comment by felixwortmann** [comment]
Thank you, I have just tried it out and unfortunately it does not work for me. The version is: `vrouter: 1.1.0+20` and [this](https://github.com/lulupointu/vrouter/issues/38#issuecomment-817020248) still happens like before.

**Comment by lulupointu** [comment]
Can you try `flutter clean` then `flutter pub get`.
I did try again and it is working for me.

**Comment by felixwortmann** [comment]
I am sorry, it is still not working like before. <br>
Maybe this can help:  If I am on `/details/xyz/add/xyz` and I use `pop()`, it closes the app.
If I am on `/details/add` (I do not need a path param here) and I use `pop()`, it just goes back to `/` like expected. <br>
This works in all cases though (but it is just a workaround imo)
```dart
context.vRouter.push(context.vRouter.previousUrl!);
```

**Comment by lulupointu** [comment]
Can you tell me if the code bellow works or not ? 

```dart
import 'package:flutter/material.dart';
import 'package:vrouter/vrouter.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return VRouter(
      routes: [
        VWidget(
          path: '/',
          name: '/',
          widget: HomePage(),
          stackedRoutes: [
            VWidget(
              name: '/details',
              path: '/details/:item',
              widget: DetailsPage(),
              stackedRoutes: [
                VWidget(path: 'add/:otherItem', widget: AddPage()),
              ],
            ),
          ],
        ),
        VWidget(path: 'add/:item', widget: AddPage()),
      ],
    );
  }
}

class HomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: RaisedButton(
            child: Text('HomePage'), onPressed: () => context.vRouter.push('/details/2')));
  }
}

class DetailsPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: RaisedButton(
            child: Text('DetailsPage'), onPressed: () => context.vRouter.push('add/2')));
  }
}

class AddPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: RaisedButton(child: Text('AddPage'), onPressed: () {
          context.vRouter.pop();
        }));
  }
}
```

If it does **not** can you tell me where you are trying to run this? on the web, ios, android ?...

If it **does** work, please tell me what is different between this and what you are trying to achieve, maybe did I misunderstood!

**Comment by felixwortmann** [comment]
Ok thanks, it is working now

**Comment by lulupointu** [comment]
Great!
